export const GALAXY_RADIUS = 70;

export const DEFAULT_SENTENCES = [
  // Weather
  "The sun peeked through the clouds after a drizzly morning.",
  "A gentle breeze rustled the leaves as we walked along the shoreline.",
  "Heavy rains caused flooding in several low-lying neighborhoods.",
  "It was so hot that even the birds sought shade under the palm trees.",
  "By midnight, the temperature had dropped below freezing.",
  "Thunderstorms lit up the sky with flashes of lightning.",
  "A thick fog settled over the city streets at dawn.",
  "The air smelled of ozone after the sudden hailstorm.",
  "I watched the snowflakes drift silently onto the ground.",
  "A double rainbow appeared after the rain shower.",
  "The humidity soared to uncomfortable levels by midday.",
  "Dust devils formed in the dry desert plains.",
  "The barometer readings indicated an approaching front.",
  "A sudden gust of wind knocked over the garden chairs.",
  "Light drizzle turned into a torrential downpour within minutes.",

  // Technology
  "The new smartphone features a foldable display and 5G connectivity.",
  "In the world of AI, transformers have revolutionized natural language processing.",
  "Quantum computing promises to solve problems beyond classical computers' reach.",
  "Blockchain technology is being explored for secure voting systems.",
  "Virtual reality headsets are becoming more affordable and accessible.",
  "The rise of electric vehicles is reshaping the automotive industry.",
  "Cloud computing allows businesses to scale resources dynamically.",
  "Machine learning algorithms can now predict stock market trends with surprising accuracy.",
  "Augmented reality applications are transforming retail experiences.",
  "The Internet of Things connects everyday devices to the web for smarter living.",
  "Cybersecurity threats are evolving, requiring constant vigilance.",
  "3D printing is enabling rapid prototyping and custom manufacturing.",
  "Edge computing reduces latency by processing data closer to the source.",
  "Biometric authentication methods are enhancing security in devices.",
  "Wearable technology is tracking health metrics in real-time.",
  "Artificial intelligence is being used to create realistic deepfakes.",

  // Cooking
  "Preheat the oven to 375°F before you start mixing the batter.",
  "She finely chopped the garlic and sautéed it in two tablespoons of olive oil.",
  "A pinch of saffron adds a beautiful color and aroma to traditional paella.",
  "If the soup is too salty, add a peeled potato to absorb excess sodium.",
  "Let the bread dough rise for at least an hour in a warm, draft-free spot.",
  "Marinate the chicken overnight in a blend of citrus and spices.",
  "Use a cast-iron skillet to sear the steak on high heat.",
  "Whisk the egg whites until they form stiff peaks.",
  "Fold in the chocolate chips gently to keep the batter airy.",
  "Brush the pastry with an egg wash for a golden finish.",
  "Slow-roast the pork shoulder until it falls off the bone.",
  "Garnish the salad with toasted nuts and fresh herbs.",
  "Deglaze the pan with white wine for a rich sauce.",
  "Simmer the curry paste until the aroma intensifies.",
  "Let the risotto rest before serving to thicken slightly.",

  // Sports
  "He dribbled past two defenders and sank a three-pointer at the buzzer.",
  "The marathon runner kept a steady pace despite the sweltering heat.",
  "Their home team clinched the championship with a last-minute goal.",
  "NASCAR fans cheered as the cars roared around the oval track.",
  "She landed a perfect triple axel at the figure skating championship.",
  "The cyclist pedaled up the steep hill in record time.",
  "He pitched a no-hitter during the high school baseball game.",
  "The quarterback threw a touchdown pass under heavy pressure.",
  "They scored a hat-trick in the hockey final.",
  "The boxer delivered a swift uppercut in the final round.",
  "Surfers caught massive waves at dawn on the Pacific coast.",
  "Fans erupted when the underdog scored the winning goal.",
  "The swimmer broke the national record in the 200m freestyle.",
  "The gymnast executed a flawless routine on the balance beam.",
  "The rugby team celebrated their victory with a traditional haka.",

  // Finance
  "The stock market rallied after positive earnings reports.",
  "Investors are closely watching interest rate changes by the Federal Reserve.",
  "Cryptocurrency prices have been extremely volatile this year.",
  "Diversification is key to managing investment risk effectively.",
  "Inflation rates have reached a 40-year high, impacting consumer spending.",
  "Many companies are adopting ESG criteria to attract socially conscious investors.",
  "The bond market is reacting to geopolitical tensions and supply chain disruptions.",
  "Venture capital funding for startups has surged in the tech sector.",
  "Exchange-traded funds (ETFs) offer a way to invest in diversified portfolios.",
  "The global economy is recovering from the pandemic, but challenges remain.",
  "Central banks are exploring digital currencies to modernize payment systems.",
  "Retail investors are increasingly participating in the stock market through apps.",
  "Hedge funds are using complex algorithms to gain an edge in trading.",
  "Real estate prices have skyrocketed in urban areas due to low inventory.",
  "The startup raised $10 million in its Series A funding round.",

  // Music
  "The symphony orchestra played a hauntingly beautiful melody.",
  "She strummed her guitar softly, filling the room with a warm sound.",
  "The DJ mixed tracks seamlessly, keeping the crowd dancing all night.",
  "His voice soared during the high notes of the ballad.",
  "The band played an acoustic set in the intimate coffee shop.",
  "Jazz musicians often improvise solos based on the chord changes.",
  "The opera singer hit the high C with perfect pitch.",
  "The choir harmonized beautifully, filling the church with sound.",
  "He composed a symphony that was performed at the concert hall.",
  "The singer-songwriter wrote heartfelt lyrics about love and loss.",
  "The rock band headlined the festival, drawing a massive crowd.",
  "Hip-hop artists use rhythm and rhyme to tell powerful stories.",
  "The violinist played a virtuosic solo that left the audience in awe.",
  "Folk music often reflects the culture and traditions of a community.",
  "The gospel choir lifted spirits with their uplifting performance.",

  // History
  "The fall of the Berlin Wall in 1989 marked the end of the Cold War.",
  "Ancient Egypt's pyramids are a testament to their architectural prowess.",
  "Europe's Renaissance period sparked a revival in art and science.",
  "The signing of the Declaration of Independence in 1776 established the United States.",
  "The Industrial Revolution transformed economies and societies worldwide.",
  "Rome was the center of a vast empire that influenced law and governance.",
  "The discovery of the New World by Christopher Columbus in 1492 changed global trade.",
  "The French Revolution in 1789 led to significant political and social change.",
  "World War II was a global conflict that reshaped international relations.",
  "The fall of the Roman Empire in 476 AD marked the beginning of the Middle Ages.",
  "The invention of the printing press revolutionized the spread of knowledge.",
  "The Cold War was characterized by political tension between the U.S. and the Soviet Union.",
  "The ancient Silk Road connected East and West through trade routes.",
  "The signing of the Magna Carta in 1215 established principles of due process.",
  "Exploration during the Age of Discovery expanded European empires across the globe.",
];
